# 복습

In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
data = {
    "study_hours": [1, 1, 2, 3, 3, 4, 5, 6, 7, 8],
    "attendance": [50, 55, 60, 80, 60, 75, 75, 80, 90, 95],
    "pass_fail": [0, 0, 0, 1, 0, 1, 1, 1, 1, 1]
 }
df = pd.DataFrame(data)

# 입력값과 정답 분리
X = df[["study_hours", "attendance"]]
y = df["pass_fail"]

# 모델 만들기

model = DecisionTreeClassifier(random_state=42)
model.fit(X, y)

print("데이터 준비 완료")
print(f'학생 수: {len(df)}명') # 학생 수: %%명

데이터 준비 완료
학생 수: 10명

## 모델 정확도

- 학습에 사용한 데이터로 정확도 확인

In [ ]:
accuracy = model.score(X, y)
print("모델 정확도 : ", accuracy) # 0~1 표시됨 -> 0~100%로 바꿔서 표시하기 위해서는 *100 해주면 됨
print(f"모델 정확도 퍼센트 : {accuracy * 100:.0f}%") # 소수점 n자리까지 표시하기 위해서는 :.nf 해주면 됨

모델 정확도 :  1.0
모델 정확도 퍼센트 : 100%

In [31]:
prediction = model.predict(X) # 모델이 어떤 예측을 했는지   

# Columns - 공부시간, 출석률, 실제값, 예측값, 결과값
# zip() => zip([1, 2, 3], [4, 5, 6]) => [(1, 4), (2, 5), (3, 6)]
# 실제값과 예측값을 한상으로 묶음
result = pd.DataFrame({
    "공부시간": X["study_hours"].values,
    "출석률": X["attendance"].values,
    "실제값": y.values,
    "예측값": prediction,
    "결과값": [ "합격" if a == p else "불합격" for a, p in zip(y, prediction) ]
    }) 


# "공부시간": "~~",
# "출석률": "~~",
# "실제값": "~~",
# "예측값": "~~",
# "결과값": "~~" 

result

   공부시간  출석률  실제값  예측값 결과값
0     1   50    0    0  합격
1     1   55    0    0  합격
2     2   60    0    0  합격
3     3   80    1    1  합격
4     3   60    0    0  합격
5     4   75    1    1  합격
6     5   75    1    1  합격
7     6   80    1    1  합격
8     7   90    1    1  합격
9     8   95    1    1  합격

# 딕셔너리

Key-Value 한 쌍으로 이루어진 집합(자료형)

- List => 번호표가 있는 사물함 (0번, 1번, 2번, ...)
- Dictionary => 이름표가 있는 사물함 (학번, 이름, 학년, ...)

In [ ]:
# 리스트
student_list = ["KIM", 20, 50, "LEE", "PARK"]
print(f'리스트에서 이름 출력 : {student_list[0]}') # 'KIM'

# 딕셔너리
student_dict = {"name": "KIM", "age": 20, "score": 50}
print(f'딕셔너리에서 이름 출력 : {student_dict["name"]}') # 'KIM'
print(f'딕셔너리에서 나이 출력 : {student_dict["age"]}') # 20
print(f'딕셔너리에서 점수 출력 : {student_dict["score"]}') # 50

person = {
    "name": "KIM",
    "age": 20,
    "major": "AI응용프로그래밍"
}
# 전체 출력
print(f'이름 : {person["name"]}, 나이 : {person["age"]}, 전공 : {person["major"]}')

리스트에서 이름 출력 : KIM
딕셔너리에서 이름 출력 : KIM
딕셔너리에서 나이 출력 : 20
딕셔너리에서 점수 출력 : 50
이름: KIM, 나이: 20, 전공: AI응용프로그래밍

In [ ]:
person["age"] = 21
print(f'나이 : {person["age"]}', person) # 21

# 성별 추가
person["gender"] = "Male"
print(person)

# 성별 삭제
del person["gender"] 
print(person)

나이 : 21 {'name': 'KIM', 'age': 21, 'major': 'AI응용프로그래밍', 'gender': 'Male'}
{'name': 'KIM', 'age': 21, 'major': 'AI응용프로그래밍', 'gender': 'Male'}
{'name': 'KIM', 'age': 21, 'major': 'AI응용프로그래밍'}

# 문제

- 사과, 바나나, 포도는 각 1000원, 2000원, 3000원 이다.  
    - 딕셔너리 로그 출력 
- 사과의 가격을 10% 할인하고 바나나는 13% 인상했을 때,  
    - Python 코드로 작성
- 사과, 바나나, 포도의 가격표를 표시하세요. (DataFrame 사용)  
    - 로그 출력

In [75]:
fruits = {
    "사과": 1000,
    "바나나": 2000,
    "포도": 3000
}
print(fruits)

fruits["사과"] = int(fruits["사과"] * 0.9) 
fruits["바나나"] = int(fruits["바나나"] * 1.13) 

import pandas as pd
 
price_list = pd.DataFrame({
    "과일": list(fruits.keys()),
    "가격(원)": list(fruits.values())
})

print(price_list)

{'사과': 1000, '바나나': 2000, '포도': 3000}
    과일  가격(원)
0   사과    900
1  바나나   2260
2   포도   3000

## 딕셔너리와 반복문 함께 사용

In [27]:
scores = {
    "국어": 88,
    "수학": 76,
    "영어": 85
}
# 로그 출력 ------
# 국어 : 88점
# 수학 : 76점
# 영어 : 85점
for subject, score in scores.items():
    print(f'{subject} : {score}점')

국어 : 88점
수학 : 76점
영어 : 85점

In [29]:
# 80점 이상인 과목만 출력
for subject, score in scores.items():
    if score >= 80:
        print(f'{subject} : {score}점')

국어 : 88점
영어 : 85점

# Pandas DataFrame 다루기

In [30]:
data = {
    "study_hours": [1, 1, 2, 3, 3, 4, 5, 6, 7, 8],
    "attendance": [50, 55, 60, 80, 60, 75, 75, 80, 90, 95],
    "pass_fail": [0, 0, 0, 1, 0, 1, 1, 1, 1, 1]
 }
df = pd.DataFrame(data)
df

   study_hours  attendance  pass_fail
0            1          50          0
1            1          55          0
2            2          60          0
3            3          80          1
4            3          60          0
5            4          75          1
6            5          75          1
7            6          80          1
8            7          90          1
9            8          95          1

In [34]:
# 상위 3줄만 보기

print(df.head(3))

   study_hours  attendance  pass_fail
0            1          50          0
1            1          55          0
2            2          60          0

In [ ]:
# 기본 통계 보기
# count - 데이터 개수
# mean - 평균값
# std - 표준편차 (데이터가 평균에서 얼마나 떨어져 있는지)
# min - 최솟값
# 25% - 25% 지점의 값
# 50% - 50% 지점의 값 (중앙값)
# 75% - 75% 지점의 값
# max - 최댓값
df.describe()

       study_hours  attendance  pass_fail
count     10.00000   10.000000  10.000000
mean       4.00000   72.000000   0.600000
std        2.44949   15.129074   0.516398
min        1.00000   50.000000   0.000000
25%        2.25000   60.000000   0.000000
50%        3.50000   75.000000   1.000000
75%        5.75000   80.000000   1.000000
max        8.00000   95.000000   1.000000

In [44]:
# 조건으로 데이터 골라내기
high_attendance = df[df["attendance"] >= 70]
print(high_attendance)

# 합격한 학생만 출력
passed_students = df[df["pass_fail"] == 1]
print(passed_students)

   study_hours  attendance  pass_fail
3            3          80          1
5            4          75          1
6            5          75          1
7            6          80          1
8            7          90          1
9            8          95          1
   study_hours  attendance  pass_fail
3            3          80          1
5            4          75          1
6            5          75          1
7            6          80          1
8            7          90          1
9            8          95          1

# 날씨 예측

In [54]:
# 데이터 준비
weather_data = {
    "clouds":   [10, 20, 30, 50, 60, 70, 80, 90, 95, 40],
    "humidity": [30, 35, 40, 55, 65, 70, 80, 85, 90, 45],
    "umbrella": [0 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 1 , 0 ]
}

weather_df = pd.DataFrame(weather_data)
weather_df

   clouds  humidity  umbrella
0      10        30         0
1      20        35         0
2      30        40         0
3      50        55         0
4      60        65         1
5      70        70         1
6      80        80         1
7      90        85         1
8      95        90         1
9      40        45         0

In [57]:
# 입력값과 정답 분리
X_weather = weather_df[["clouds", "humidity"]]
y_weather = weather_df["umbrella"]

print("입력값과 정답 분리 완료!")

입력값과 정답 분리 완료!

In [58]:
# 모델 만들기 + 학습
weather_model = DecisionTreeClassifier(random_state=42)
weather_model.fit(X_weather, y_weather)
print("모델 학습 완료!")

모델 학습 완료!

In [ ]:
# 예측하기
test_weather = pd.DataFrame([
    [20,35], #구름 적음, 습도 낮음
    [55,60], #구름 보통, 습도 보통
    [85,88], #구름 많음, 습도 높음
], columns=["clouds", "humidity"])

prediction = weather_model.predict(test_weather)
prediction

array([0, 0, 1])

## 문제

아래 로그 개별 출력 ---
- 구름 ?%, 습도 ?% -> 우산 필요 여부 : ?
    - 예시) 구름 20%, 습도35% -> 우산 불필요

In [62]:
weather = pd.DataFrame({
    "구름": X_weather["clouds"].values,
    "습도": X_weather["humidity"].values,
    "우산 필요 여부": y_weather.values
    }) 

weather

   구름  습도  우산 필요 여부
0  10  30         0
1  20  35         0
2  30  40         0
3  50  55         0
4  60  65         1
5  70  70         1
6  80  80         1
7  90  85         1
8  95  90         1
9  40  45         0

In [61]:
# 모델 정확도 구하기

acc = weather_model.score(X_weather, y_weather)
print(f"모델 정확도: {acc}")
print(f"모델 정확도 퍼센트: {acc * 100:.0f}%")

모델 정확도: 1.0
모델 정확도 퍼센트: 100%

In [ ]:
# 모델 정확도 낮추기
# 애매한 데이터를 포함한 날씨 데이터
 
messy_data = {
    "cloudy":   [10, 20, 55, 55, 60, 70, 80, 90],
    "humidity": [30, 35, 60, 60, 65, 70, 80, 85],
    "umbrella": [0 , 0 , 0 , 1 , 1 , 1 , 1 , 1],
}
 
messy_df = pd.DataFrame(messy_data)
 
X_messy = messy_df[["cloudy", "humidity"]]
Y_messy = messy_df["umbrella"]
 
messy_model = DecisionTreeClassifier(random_state=42)
messy_model.fit(X_messy, Y_messy)
 
messy_acc = messy_model.score(X_messy, Y_messy)
print(f"애매한 데이터 포함 모델 정확도: {messy_acc * 100}%")
 
print()
 
messy_pred = messy_model.predict(X_messy)
result = pd.DataFrame(
    {
        "구름": X_messy["cloudy"].values,
        "습도": X_messy["humidity"].values,
        "실제": Y_messy.values,
        "예측": messy_pred,
        "결과": ["0" if a == p else "X" for a, p in zip(Y_messy, messy_pred)]
    }
)

result

애매한 데이터 포함 모델 정확도: 87.5%

   구름  습도  실제  예측 결과
0  10  30   0   0  0
1  20  35   0   0  0
2  55  60   0   0  0
3  55  60   1   0  X
4  60  65   1   1  0
5  70  70   1   1  0
6  80  80   1   1  0
7  90  85   1   1  0